# Generated by Django 2.0.4 on 2018-05-31 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('municipio', models.CharField(help_text='Informe o município da sede da cooperativa', max_length=100)),
                ('categoria', models.CharField(choices=[('1', 'Categoria 1'), ('2', 'Categoria 2'), ('3', 'Categoria 3'), ('4', 'Categoria 4')], max_length=100)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(help_text='Em kg. Ex: 2000 para 2 toneladas do produto')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galpao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.PositiveIntegerField(help_text='Em kg. Ex: 2000 para 2 toneladas de capacidade')),
                ('endereco', models.CharField(help_text='Informe o endereço', max_length=100)),
                ('categoria', models.CharField(choices=[('1', 'Categoria 1'), ('2', 'Categoria 2'), ('3', 'Categoria 3'), ('4', 'Categoria 4')], max_length=100)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço por quilograma', max_digits=10, verbose_name='Preço (R$)')),
                ('validade', models.PositiveIntegerField(help_text='Tempo dado em dias', verbose_name='Tempo de validade')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='estoque',
            name='galpao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Galpao'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooperativa.Produto'),
        ),
    ]
