# Generated by Django 2.0.4 on 2018-04-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='cep',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='circunstancia_lesao',
            field=models.CharField(blank=True, help_text='CID 10 - Cap XX', max_length=5, null=True, verbose_name='Circunstâncias da lesão'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='codigo_ibge_ocorrencia',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código (IBGE) (Ocorrência)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='codigo_ibge_residencia',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código (IBGE) (Residência)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='codigo_ocorrencia',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento (apto, casa, ...'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='complemento_ocorrencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento (apto, casa, ...)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='deficiencia',
            field=models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], max_length=100, null=True, verbose_name='Possui algum tipo de deficiência/transtorno?'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='deficiencia_se_sim',
            field=models.CharField(blank=True, choices=[('1', 'Deficiência Física'), ('2', 'Deficiência Intelectual'), ('3', 'Deficiência Visual'), ('4', 'Deficiência auditiva'), ('5', 'Transtorno mental'), ('6', 'Transtorno  de comportamento'), ('9', 'Outras')], max_length=200, null=True, verbose_name='Se sim, qual tipo de deficiência/transtorno?'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='distrito',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='distrito_ocorrencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('1', 'Solteiro'), ('2', 'Casado/união consensual'), ('3', 'Viúvo'), ('4', ' Separado'), ('8', 'Não se aplica'), ('9', 'Ignorado')], max_length=100, null=True, verbose_name='Situação conjugal/Estado civil'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='geo_campo1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geo campo 1'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='geo_campo2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geo campo 2'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='geo_campo3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geo campo 3'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='geo_campo4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Geo campo 4'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='idade_agressor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=[('1', 'Criança (0 a 9 anos)'), ('2', 'Adolecente (10 a 19 anos)'), ('3', 'Jovem (20 a 24 anos)'), ('4', 'Pessoa adulta (25 a 59 anos'), ('5', 'Pessoa idosa ( 60 anos ou mais'), ('9', 'Ignorado')]),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='identidade_genero',
            field=models.CharField(blank=True, choices=[('1', 'Travesti'), ('2', 'Mulher Transexual'), ('3', 'Homem Transexual'), ('8', 'Não se aplica'), ('9', 'Ignorado')], max_length=100, null=True, verbose_name='Identidade de gênero'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='nome_acompanhante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do acompanhante'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='nome_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='notificador_codigo_unidadesaude',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Cod. da Unid. de Saúde/CNES'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='notificador_funcao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='notificador_municipio_unidadesaude',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Município/Unidade de Saúde'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='notificador_nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='observacoes_adicionais',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Observações Adicionais'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='orientacao_sexual',
            field=models.CharField(blank=True, choices=[('1', 'Heterossexual'), ('2', 'Homossexual (gay/lesbuca)'), ('3', 'Bissexual'), ('8', 'Não se aplica'), ('9', 'Ignorado')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='pais_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País (se residente fora do Brasil'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='parentesco_acompanhante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vinculo/grau de parentesco'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de Referência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='ponto_referencia_ocorrencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ponto de referência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='telefone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='telefone_acompanhante',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='(DDD) Telefone'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='uf_ocorrencia',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='uf_residencia',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF (residência)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='violencia_trabalho',
            field=models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('9', 'Ignorado')], max_length=20, null=True, verbose_name='Violência Relacionada ao Trabalho'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='violencia_trabalho_se_sim',
            field=models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não'), ('2', 'Não se aplica'), ('9', 'Ignorado')], max_length=20, null=True, verbose_name='Se sim, foi emitida a Comunicaçao de Acidente de Trabalho (CAT)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='zona_moradia',
            field=models.CharField(blank=True, choices=[('1', 'Urbana'), ('2', 'Rural'), ('3', 'Periurbana'), ('9', 'Ignorado')], max_length=20, null=True, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='zona_ocorrencia',
            field=models.CharField(blank=True, choices=[('', 'Urbana'), ('', 'Rural'), ('', 'Periurbana'), ('', 'Ignorado')], max_length=100, null=True, verbose_name='Zona'),
        ),
    ]
