# Generated by Django 2.0.4 on 2018-05-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0003_auto_20180423_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento(apto, casa) '),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='complemento_ocorrencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento(apto, casa)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_notificacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='hora_ocorrencia',
            field=models.CharField(help_text='(00:00 - 23:59)', max_length=5),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='idade_agressor',
            field=models.CharField(blank=True, choices=[('1', 'Criança (0 a 9 anos)'), ('2', 'Adolecente (10 a 19 anos)'), ('3', 'Jovem (20 a 24 anos)'), ('4', 'Pessoa adulta (25 a 59 anos)'), ('5', 'Pessoa idosa ( 60 anos ou mais)'), ('9', 'Ignorado')], max_length=100, null=True, verbose_name='Ciclo de vida do provável autor da violência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='pais_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País (se residente fora do Brasil)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_violencia_sexual',
            field=models.CharField(choices=[('1', 'Assédio sexual'), ('2', 'Estupro'), ('3', 'Pornografia infantil'), ('4', 'Exploração sexual'), ('9', 'Outros')], max_length=200, verbose_name='Se ocorreu violência sexual, qual o tipo?'),
        ),
    ]
