# Generated by Django 2.0.4 on 2018-05-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0004_auto_20180430_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='data_ocorrencia',
            new_name='dataocorrencia',
        ),
    ]
