# Generated by Django 2.0.4 on 2018-05-27 02:54

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cap', '0006_auto_20180507_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name=2000)),
                ('data', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observação',
                'verbose_name_plural': 'Observações',
            },
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='agravo_doenca',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='codigo_cid10',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='codigo_cnes',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='codigo_ibge_notificacao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='codigo_ibge_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='codigo_ibge_residencia',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='codigo_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='codigo_unidade',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='data_notificacao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='distrito_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='geo_campo1',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='geo_campo2',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='geo_campo3',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='geo_campo4',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='municipio_notificacao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='nome_unidade_notificadora',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='notificador_codigo_unidadesaude',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='notificador_funcao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='notificador_municipio_unidadesaude',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='notificador_nome',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='ponto_referencia',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='tipo_notificacao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='uf_notificacao',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='unidade_notificadora',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='unidade_saude',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='bairro',
            field=models.CharField(blank=True, help_text='Informe o bairro', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='bairro_ocorrencia',
            field=models.CharField(blank=True, help_text='Informe o bairro', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='gestante',
            field=models.CharField(blank=True, choices=[('1tri', '1º trimestre'), ('2tri', '2º trimestre'), ('3tri', '3º trimestre'), ('nao', 'Não'), ('na', 'Não se apliica')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='hora_ocorrencia',
            field=models.CharField(blank=True, help_text='(00:00 - 23:59)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='logradouro',
            field=models.CharField(blank=True, help_text='Informe a rua/avenida', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='logradouro_ocorrencia',
            field=models.CharField(blank=True, help_text='Informe a rua/avenida', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='meio_agressao',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FCE', 'Forca corporal/espancamento'), ('EN', 'Enforcamento'), ('OC', 'Objeto contundente'), ('OPC', 'Objeto pérfuro-cortante'), ('SOQ', 'Substâncias/Objeto quente'), ('EI', 'Envenenamento/Intoxicação'), ('AF', 'Arma de fogo'), ('AM', 'Ameaça'), ('OU', 'Outros')], max_length=200, verbose_name='Meio de agressão'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='motivo_violencia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SE', 'Sexismo'), ('HO', 'Homofobia'), ('RA', 'Racismo'), ('IR', 'Intolerancia religiosa'), ('XE', 'Xenofobia'), ('CG', 'Conflito geracional'), ('SR', 'Situação de rua'), ('DE', 'Deficiencia'), ('OU', 'Outros')], max_length=200, verbose_name='Essa violencia foi motivada por'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='municipio_ocorrencia',
            field=models.CharField(blank=True, help_text='Informe onde houve a ocorrencia', max_length=100, null=True, verbose_name='Município da ocorrência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='municipio_residencia',
            field=models.CharField(blank=True, help_text='Informe seu endereço', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='nome',
            field=models.CharField(blank=True, help_text='Informe o nome do paciente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='numero_ocorrencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='numero_residencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='procedimento_realizado',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PDST', 'Profilaxia DST'), ('PHIV', 'Profilaxia HIV'), ('PHB', 'Profilaxia Hepatite B'), ('CSA', 'Coleta de sangue'), ('CSE', 'Coleta de sémen'), ('CSV', 'Coleta de secreção vaginal'), ('CE', 'Contracepção de emergência'), ('APL', 'Aborto previsto em lei')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='raca_cor',
            field=models.CharField(blank=True, choices=[('BRANCO', 'Branco'), ('PRETO', 'Preto'), ('AMARELO', 'Amarelo'), ('PARDO', 'Pardo'), ('INDIGENA', 'Indigena')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_violencia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FI', 'Física'), ('PM', 'Psicológica/moral'), ('TO', 'Tortura'), ('SE', 'Sexual'), ('TSH', 'Trafico de seres humanos'), ('FE', 'Financeira/economica'), ('NA', 'Negligencia/abandono')], help_text='Informe o tipo de violência', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_violencia_sexual',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Assédio sexual'), ('2', 'Estupro'), ('3', 'Pornografia infantil'), ('4', 'Exploração sexual'), ('9', 'Outros')], max_length=200, verbose_name='Se ocorreu violência sexual, qual o tipo?'),
        ),
        migrations.AddField(
            model_name='observacoes',
            name='ocorrencia',
            field=models.ForeignKey(on_delete='cascade', to='cap.Ocorrencia'),
        ),
    ]
