# Generated by Django 2.0.4 on 2018-05-01 01:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agressor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=200, verbose_name='Nome do Autor(a)')),
                ('rg_autor', models.CharField(blank=True, max_length=15, null=True, verbose_name='RG')),
                ('autor_foi_preso', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, verbose_name='Autor Já Foi Preso')),
                ('autor_doenca_psicologica', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, verbose_name='Autor Recebe Atendimento Psicológico/Psiquiátrico')),
                ('autor_necessita_atendimento_psicologica', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, verbose_name='Autor Necessita de Atendimento Psicológico/Psiquiátrico')),
                ('autor_suicidio', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, verbose_name='Autor Já Ameaçou ou Tentou Suicídio')),
                ('autor_arma', models.CharField(choices=[('1', 'Sim'), ('2', 'Não'), ('3', 'Sim e já Utilizou Contra a Vítima ou Terceiros'), ('4', 'Não Soube Informar')], max_length=100, verbose_name='O Autor Possui Arma de Fogo ou Arma Branca')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_fato', models.CharField(choices=[('', 'Manhã (06:00 - 12:00)'), ('', 'Tarde (12:00 - 18:00)'), ('', 'Noite (18:00 - 24:00)'), ('', 'Madrugada (24:00 - 06:00)')], max_length=100, verbose_name='Período do Fato')),
                ('ambiente_agressao', models.CharField(choices=[('1', 'Residência em Comum com o Agressor'), ('2', 'Residência Exclusiva da Vítima'), ('3', 'Residência de Terceiros'), ('4', 'Profissional'), ('5', 'Local Público'), ('6', 'Redes Sociais'), ('7', 'Telefone'), ('8', 'Outros')], help_text='Marque todas que se aplicam', max_length=100, verbose_name='Ambiente da Agressão')),
                ('ambiente_agressao_outros', models.CharField(max_length=300, verbose_name='Outros')),
                ('vinculo_agressor', models.CharField(choices=[('1', 'Agregado Na Unidade Doméstica'), ('2', 'Cônjuge/Companheiro'), ('3', 'Namorado(a)'), ('4', 'Ex-Cônjuge/Compenheiro(a)'), ('5', 'Ex-Namorado(a)'), ('6', 'Pai'), ('7', 'Mãe'), ('8', 'Padrastro'), ('9', 'Madrasta'), ('10', 'Filho(a)'), ('11', 'Irmão(a)'), ('12', 'Avo(a)'), ('13', 'Tio/Tia'), ('14', 'Primo/prima'), ('15', 'Enteado(a)'), ('16', 'Cunhado(a)'), ('17', 'Genro/Nora'), ('18', 'Sogro(a)'), ('19', 'Amigo(a)'), ('20', 'Vizinho(a)'), ('21', 'Empregador(a)'), ('22', 'Outros')], max_length=100, verbose_name='Vínculo Do Agressor(a) Com a Vítima')),
                ('vinculo_agressor_outros', models.CharField(max_length=100, verbose_name='Outros')),
                ('fatores_risco', models.CharField(choices=[('1', 'Histórico de Violência Anterior Entre o Mesmo Agressor e Vítima'), ('2', 'Histórico de Violência Pelo Agressor Contra Outras Pessoas ou Animais'), ('3', 'Uso de Àlcool ou Drogas Ilícitas Pelo Agressor'), ('4', 'Trantorno ou Doença Metal Pelo Agressor'), ('5', 'Comportamento Controlador, Ciúmes ou Alegaçoes de Traição'), ('6', 'Separação Ou Tentativa de Separação no Ùltimo Ano'), ('7', 'Disputa Familiar (Bens ou Filhos)'), ('8', 'Presença de Crianças ou Adolescentes No Núcleo familiar'), ('9', 'Agressor Com Acesso a Arma de Fogo (Profissional de Segurança ou Outros)'), ('10', 'Agressor Envolvido com atividades Criminosas'), ('11', 'Agressor Já Descumpriu Anteriormente Ordem Judicial de Medidas Protetivas'), ('12', 'de Urgência'), ('13', 'Vítima Com Dependência Econômica'), ('14', 'Vítima Com Fator de Vulnerabilidade (Criança, Adolescente, Idosos(a), Com'), ('15', 'deficiência)'), ('16', 'Vítima Sem Parentes Próximos ou Rede de Apoio'), ('17', 'Vítima Gestante'), ('18', 'Manteve a Vítima em Cárcere Privado'), ('19', 'Já Tentou Controlar Sua Vida (Isolar da Família, Proibir de Falar com amigos,'), ('20', 'Proibir de usar Telefone, etc)'), ('21', 'A Vítima deixou o Lar em Função da Violência'), ('22', 'Manteve Relação Sexual a Força'), ('23', 'Agride os Filhos'), ('24', 'O Autor Segue ou Vigia a Vítima'), ('25', 'Faz Chantagem ou Ameaça Pra manter o Relacionamento'), ('26', 'Teve seu pertences Danificados')], help_text='Marque todas que se aplicam', max_length=200, verbose_name='Fatores de Risco Identificados')),
                ('periodo_relacionamento', models.CharField(choices=[('1', 'Até 06 Meses'), ('2', 'De 06 Mes a 01 Ano'), ('3', 'De 01 ano a 02 Anos'), ('4', 'De 02 anos a 05 Anos'), ('5', 'De 05 Anos a 10 Anos'), ('6', 'Acima de 10 Anos')], max_length=100, verbose_name='Período De Relacionamento')),
                ('periodo_violencia', models.CharField(choices=[('1', 'Até 06 Meses'), ('2', 'De 06 Mes a 01 Ano'), ('3', 'De 01 ano a 02 Anos'), ('4', 'De 02 anos a 05 Anos'), ('5', 'De 05 Anos a 10 Anos'), ('6', 'Acima de 10 Anos')], max_length=100, verbose_name='Há Quanto Tempo Ocorre a Violência')),
                ('filhos', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, verbose_name='Possui filhos')),
                ('atendimento_medico', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, verbose_name='Houve Atendimento Médico')),
                ('tipo_violencia', models.CharField(choices=[('1', 'Física'), ('2', 'Sexual'), ('3', 'Psicológica'), ('4', 'Patrimonial'), ('5', 'Moral')], help_text='Marque todas que se aplicam', max_length=100, verbose_name='Tipo De Violência')),
                ('natureza_ocorrencia', models.CharField(choices=[('2', 'Agressão'), ('2', 'Ameaça'), ('2', 'Lesão Corporal'), ('2', 'Injúria'), ('2', 'Calúnia'), ('2', 'Difamação'), ('2', 'Pertubação do Sossego/Tranquilidade'), ('2', 'Dano'), ('2', 'Estupro'), ('2', 'Descumplimento de Ordem Judicial'), ('2', 'Cárcere Privado'), ('2', 'Outros')], help_text='Marque todas que se aplicam', max_length=100, verbose_name='Natureza Da Ocorrência')),
                ('natureza_ocorrencia_outros', models.CharField(max_length=1000, verbose_name='Outros')),
                ('acompanhamento_ppdv', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, verbose_name='Acompanhamento Pela PPVD')),
                ('data_visita_autor', models.DateField(verbose_name='Data da Visita ao Autor')),
                ('numero_reds_autor', models.CharField(max_length=20, verbose_name='Número do REDS')),
                ('observacoes_visita_autor', models.TextField(max_length=2000, verbose_name='Observações')),
                ('data_visita_vitima', models.DateField(verbose_name='Data da Visita A Vítima')),
                ('numero_reds_vitima', models.CharField(max_length=20, verbose_name='Número do REDS')),
                ('observacoes_visita_vitima', models.TextField(max_length=2000, verbose_name='Observações')),
                ('data_visita_autor_medida_protetiva', models.DateField(verbose_name='Data da Visita ao Autor')),
                ('numero_reds_autor_medida_protetiva', models.CharField(max_length=20, verbose_name='Número do REDS')),
                ('observacoes_visita_autor_medida_protetiva', models.TextField(max_length=2000, verbose_name='Observações')),
                ('data_visita_vitima_medida_protetiva', models.DateField(verbose_name='Data da Visita A Vítima')),
                ('numero_reds_vitima_medida_protetiva', models.CharField(max_length=20, verbose_name='Número do REDS')),
                ('observacoes_visita_vitima_medida_protetiva', models.TextField(max_length=2000, verbose_name='Observações')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policia_militar.Agressor')),
            ],
        ),
        migrations.CreateModel(
            name='Vitima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100)),
                ('data_nascimento', models.DateField()),
                ('municipio_residencia', models.CharField(help_text='Informe seu endereço', max_length=100)),
                ('bairro', models.CharField(help_text='Informe o bairro', max_length=100)),
                ('logradouro', models.CharField(help_text='Informe a rua/avenida', max_length=100)),
                ('telefone', models.CharField(max_length=10)),
                ('idade', models.CharField(max_length=50, verbose_name=[('1', '15 a 17 Anos'), ('2', '18 a 25 anos'), ('3', '25 a 30 anos'), ('4', '30 a 35 anos'), ('5', '35 a 40 anos'), ('6', 'Mais de 40 anos'), ('7', 'Outros')])),
                ('idade_outros', models.CharField(max_length=50)),
                ('raca_cor', models.CharField(choices=[('BRANCO', 'Branco'), ('PRETO', 'Preto'), ('AMARELO', 'Amarelo'), ('PARDO', 'Pardo'), ('INDIGENA', 'Indigena')], max_length=100)),
                ('medida_protetiva', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, verbose_name='Possui Medida Protetiva')),
                ('deficiencia', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Não informado'), ('2', 'Não Possui'), ('3', 'Física'), ('4', 'Auditiva'), ('5', 'Visual'), ('6', 'Mental'), ('7', 'Múltiplas')], help_text='Marque todas que se aplicam', max_length=13, verbose_name='Deficiência')),
                ('orientacao_sexual', models.CharField(blank=True, choices=[('1', 'Heterossexual'), ('2', 'Homossexual'), ('3', 'Bissexual'), ('4', 'Outros'), ('5', 'Não Informado')], max_length=100, null=True)),
                ('instrucao', models.CharField(choices=[('1', 'Não Informado'), ('2', 'Não Alfabetizado'), ('3', 'Fundamental Incompleto'), ('4', 'Fundamental Completo'), ('5', 'Médio Incompleto'), ('6', 'Médio Completo'), ('7', 'Superior Incompleto'), ('8', 'Superior Incompleto')], max_length=100, verbose_name='Instrução')),
                ('renda_individual', models.CharField(choices=[('1', 'Não Informado'), ('2', 'Não Possui Renda'), ('3', 'Até 01 salário Minímo'), ('4', 'De 01 até 02 salários Minímo'), ('5', 'De 02 a 05 salários Minímo'), ('6', 'De 05 a 10 salários Minímo'), ('7', 'Mais de 10 salários Minímo')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='vitima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policia_militar.Vitima'),
        ),
    ]
