# Generated by Django 2.0.4 on 2018-05-01 01:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policia_militar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='ambiente_agressao',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Residência em Comum com o Agressor'), ('2', 'Residência Exclusiva da Vítima'), ('3', 'Residência de Terceiros'), ('4', 'Profissional'), ('5', 'Local Público'), ('6', 'Redes Sociais'), ('7', 'Telefone'), ('8', 'Outros')], help_text='Marque todas que se aplicam', max_length=15, verbose_name='Ambiente da Agressão'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='fatores_risco',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Histórico de Violência Anterior Entre o Mesmo Agressor e Vítima'), ('2', 'Histórico de Violência Pelo Agressor Contra Outras Pessoas ou Animais'), ('3', 'Uso de Àlcool ou Drogas Ilícitas Pelo Agressor'), ('4', 'Trantorno ou Doença Metal Pelo Agressor'), ('5', 'Comportamento Controlador, Ciúmes ou Alegaçoes de Traição'), ('6', 'Separação Ou Tentativa de Separação no Ùltimo Ano'), ('7', 'Disputa Familiar (Bens ou Filhos)'), ('8', 'Presença de Crianças ou Adolescentes No Núcleo familiar'), ('9', 'Agressor Com Acesso a Arma de Fogo (Profissional de Segurança ou Outros)'), ('10', 'Agressor Envolvido com atividades Criminosas'), ('11', 'Agressor Já Descumpriu Anteriormente Ordem Judicial de Medidas Protetivas'), ('12', 'de Urgência'), ('13', 'Vítima Com Dependência Econômica'), ('14', 'Vítima Com Fator de Vulnerabilidade (Criança, Adolescente, Idosos(a), Com'), ('15', 'deficiência)'), ('16', 'Vítima Sem Parentes Próximos ou Rede de Apoio'), ('17', 'Vítima Gestante'), ('18', 'Manteve a Vítima em Cárcere Privado'), ('19', 'Já Tentou Controlar Sua Vida (Isolar da Família, Proibir de Falar com amigos,'), ('20', 'Proibir de usar Telefone, etc)'), ('21', 'A Vítima deixou o Lar em Função da Violência'), ('22', 'Manteve Relação Sexual a Força'), ('23', 'Agride os Filhos'), ('24', 'O Autor Segue ou Vigia a Vítima'), ('25', 'Faz Chantagem ou Ameaça Pra manter o Relacionamento'), ('26', 'Teve seu pertences Danificados')], help_text='Marque todas que se aplicam', max_length=68, verbose_name='Fatores de Risco Identificados'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='natureza_ocorrencia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2', 'Agressão'), ('2', 'Ameaça'), ('2', 'Lesão Corporal'), ('2', 'Injúria'), ('2', 'Calúnia'), ('2', 'Difamação'), ('2', 'Pertubação do Sossego/Tranquilidade'), ('2', 'Dano'), ('2', 'Estupro'), ('2', 'Descumplimento de Ordem Judicial'), ('2', 'Cárcere Privado'), ('2', 'Outros')], help_text='Marque todas que se aplicam', max_length=23, verbose_name='Natureza Da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_violencia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Física'), ('2', 'Sexual'), ('3', 'Psicológica'), ('4', 'Patrimonial'), ('5', 'Moral')], help_text='Marque todas que se aplicam', max_length=9, verbose_name='Tipo De Violência'),
        ),
    ]
