# Generated by Django 2.0.4 on 2018-05-07 23:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policia_militar', '0002_auto_20180430_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='ambiente_agressao_outros',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Caso outros:'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_visita_autor_medida_protetiva',
            field=models.DateField(verbose_name='Data da Visita ao Autor (Medida Protetiva)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_visita_vitima_medida_protetiva',
            field=models.DateField(verbose_name='Data da Visita A Vítima (Medida Protetiva)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='natureza_ocorrencia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Agressão'), ('2', 'Ameaça'), ('3', 'Lesão Corporal'), ('4', 'Injúria'), ('5', 'Calúnia'), ('6', 'Difamação'), ('7', 'Pertubação do Sossego/Tranquilidade'), ('8', 'Dano'), ('9', 'Estupro'), ('0', 'Descumplimento de Ordem Judicial'), ('11', 'Cárcere Privado'), ('12', 'Outros')], help_text='Marque todas que se aplicam', max_length=25, verbose_name='Natureza Da Ocorrência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='natureza_ocorrencia_outros',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Caso outros:'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='periodo_fato',
            field=models.CharField(choices=[('1', 'Manhã (06:00 - 12:00)'), ('2', 'Tarde (12:00 - 18:00)'), ('3', 'Noite (18:00 - 24:00)'), ('4', 'Madrugada (24:00 - 06:00)')], max_length=100, verbose_name='Período do Fato'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='vinculo_agressor_outros',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caso outros:'),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='idade',
            field=models.CharField(choices=[('1', '15 a 17 Anos'), ('2', '18 a 25 anos'), ('3', '25 a 30 anos'), ('4', '30 a 35 anos'), ('5', '35 a 40 anos'), ('6', 'Mais de 40 anos'), ('7', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='idade_outros',
            field=models.CharField(max_length=50, verbose_name='Caso outros:'),
        ),
    ]
