# Generated by Django 2.0.4 on 2018-05-20 19:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policia_militar', '0003_auto_20180507_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitima',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='fatores_risco',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Histórico de Violência Anterior Entre o Mesmo Agressor e Vítima'), ('2', 'Histórico de Violência Pelo Agressor Contra Outras Pessoas ou Animais'), ('3', 'Uso de Àlcool ou Drogas Ilícitas Pelo Agressor'), ('4', 'Trantorno ou Doença Metal Pelo Agressor'), ('5', 'Comportamento Controlador, Ciúmes ou Alegaçoes de Traição'), ('6', 'Separação Ou Tentativa de Separação no Ùltimo Ano'), ('7', 'Disputa Familiar (Bens ou Filhos)'), ('8', 'Presença de Crianças ou Adolescentes No Núcleo familiar'), ('9', 'Agressor Com Acesso a Arma de Fogo (Profissional de Segurança ou Outros)'), ('10', 'Agressor Envolvido com atividades Criminosas'), ('11', 'Agressor Já Descumpriu Anteriormente Ordem Judicial de Medidas Protetivas de Urgência'), ('12', 'Vítima Com Dependência Econômica'), ('13', 'Vítima Com Fator de Vulnerabilidade (Criança, Adolescente, Idosos(a), Com deficiência)'), ('14', 'Vítima Sem Parentes Próximos ou Rede de Apoio'), ('15', 'Vítima Gestante'), ('16', 'Manteve a Vítima em Cárcere Privado'), ('17', 'Já Tentou Controlar Sua Vida (Isolar da Família, Proibir de Falar com amigos, Proibir de usar Telefone, etc)'), ('28', 'A Vítima deixou o Lar em Função da Violência'), ('19', 'Manteve Relação Sexual a Força'), ('20', 'Agride os Filhos'), ('21', 'O Autor Segue ou Vigia a Vítima'), ('22', 'Faz Chantagem ou Ameaça Pra manter o Relacionamento'), ('23', 'Teve seu pertences Danificados')], help_text='Marque todas que se aplicam', max_length=59, verbose_name='Fatores de Risco Identificados'),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='idade_outros',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Caso outros:'),
        ),
    ]
