# Generated by Django 2.0.4 on 2018-05-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia_militar', '0004_auto_20180520_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='agressor',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
