# Generated by Django 2.0.4 on 2018-05-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia_militar', '0005_auto_20180520_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_visita_autor',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Visita ao Autor'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_visita_autor_medida_protetiva',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Visita ao Autor (Medida Protetiva)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_visita_vitima',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Visita A Vítima'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_visita_vitima_medida_protetiva',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Visita A Vítima (Medida Protetiva)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='numero_reds_autor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do REDS'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='numero_reds_autor_medida_protetiva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do REDS'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='numero_reds_vitima',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do REDS'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='numero_reds_vitima_medida_protetiva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do REDS'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='observacoes_visita_autor',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='observacoes_visita_autor_medida_protetiva',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='observacoes_visita_vitima',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='observacoes_visita_vitima_medida_protetiva',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observações'),
        ),
    ]
