# Generated by Django 2.0.4 on 2018-05-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industria', '0002_empresa_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='maximo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='minimo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='necessidade',
        ),
        migrations.AddField(
            model_name='estoque',
            name='maximo',
            field=models.PositiveIntegerField(default=3000, help_text='Ex: 2000 para 2 toneladas do produto', verbose_name='Volume máximo suportado (kg)'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='minimo',
            field=models.PositiveIntegerField(default=100, help_text='Ex: 2000 para 2 toneladas do produto', verbose_name='Volume mínimo necessário (kg)'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='necessidade',
            field=models.PositiveIntegerField(default=1000, help_text='Ex: 2000 para 2 toneladas do produto', verbose_name='Necessidade média mensal (kg)'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=700, help_text='Ex: 2000 para 2 toneladas do produto', verbose_name='Quantidade atual em estoque (kg)'),
        ),
    ]
